/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface VlqMap {
  mappings: string
  sources?: Array<string | undefined | null> | undefined | null
  sourcesContent?: Array<string | undefined | null> | undefined | null
  names?: Array<string> | undefined | null
  lineOffset?: number | undefined | null
  columnOffset?: number | undefined | null
}
export class SourceMap {
  static mergeMaps(vlqMaps: Array<String | VlqMap>): SourceMap
  setSourceContent(sourceIndex: number, sourceContent: string): void
  getSourceContent(sourceIndex: number): string
  toUrl(): string
  toComment(): string
  toString(): string
  toMap(): {
    version: number
    mappings: string
    names: string[]
    sources: (string | null)[]
    sourcesContent: (string | null)[]
    file?: string | null
    sourceRoot?: string | null
  }
}
