/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface VlqMap {
  mappings: string
  sources?: Array<string> | undefined | null
  sourcesContent?: Array<string> | undefined | null
  names?: Array<string> | undefined | null
  lineOffset?: number | undefined | null
  columnOffset?: number | undefined | null
}
export class SourceMap {
  /** Create Speedy SourceMap from external Sourcemap instance. It's useful when storing cache on Node.js side */
  static newFromExternalSourcemap(
    external: ExternalObject<SpeedySourceMap>,
  ): SourceMap
  static mergeMaps(vlqMaps: Array<String | VlqMap>): SourceMap
  /** Convert Speedy SourceMap to External Value which can be stored in Node.js side indefinitely and useful when making mapChains or any caches */
  toExternalSourcemap(): ExternalObject<SpeedySourceMap>
  toUrl(): string
  toComment(): string
  toString(): string
  toMap(): {
    version: number
    mappings: string
    names: string[]
    sources: (string | null)[]
    sourcesContent: (string | null)[]
    file?: string | null
    sourceRoot?: string | null
  }
}
