/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface OriginalLocation {
  originalLine: number
  originalColumn: number
  source: number
  name?: number | undefined | null
}
export interface Mapping {
  generatedLine: number
  generatedColumn: number
  original?: OriginalLocation | undefined | null
}
export interface Vlq {
  mappings: string
  names: Array<string>
  sources: Array<string>
  sourcesContent: Array<string>
}
export interface VlqMap {
  mappings: string
  sources?: Array<string> | undefined | null
  sourcesContent?: Array<string> | undefined | null
  names?: Array<string> | undefined | null
  lineOffset?: number | undefined | null
  columnOffset?: number | undefined | null
}
export class SourceMap {
  static mergeMaps(vlqMaps: Array<String | VlqMap>): SourceMap
  toComment(): string
  toString(): string
  toMap(): {
    version: number
    mappings: string
    names: string[]
    sources: (string | null)[]
    sourcesContent: (string | null)[]
    file?: string | null
    sourceRoot?: string | null
  }
}
