name: Benchmark

env:
  DEBUG: 'napi:*'
  APP_NAME: 'speedy-sourcemap'
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  # https://github.com/SchrodingerZhu/snmalloc-rs
  CACHE_FRIENDLY_OFFSET: 64

'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request: null
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache cargo
        uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.settings.target }}-node@14-cargo-cache

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-lint-node@14-${{ hashFiles('pnpm-lock.yaml') }}

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile --registry https://registry.npmjs.org

      - name: Build
        run: |
          pnpm build --dir node

      - name: Run benchmark
        run: |
          pnpm bench | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'benchmarkjs'
          output-file-path: output.txt
          auto-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
