name: Lint

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-lint-node@14-${{ hashFiles('pnpm-lock.yaml') }}

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile --registry https://registry.npm.taobao.org

      - name: ESLint
        run: pnpm lint --dir node

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy